name: Test and Build Check

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test-and-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm test

      - name: Build package
        run: pnpm build
