name: Test and Build Check

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install pnpm 
        uses: pnpm/action-setup@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm test

      - name: Build package
        run: pnpm build
